# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2T79t7CrY6AOafKiMI0BFcyDnlGAt7c
"""

from google.collab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("marketing_campaign.csv",sep="\t")

df.head()

df.info()

df.isnull().sum()

df[df["Income"].isnull()]

df["Income"].describe()

df["Income"]= df["Income"].fillna(df["Income"].median())

df["Income"].isnull().sum()

df.duplicated().sum()

df["Education"].unique()

df["Marital_Status"].unique()

df["Marital_Status"].value_counts()

df[df["Marital_Status"].isin(["Alone","Absurd","YOLO"])]

df["Marital_Status"] = df["Marital_Status"].replace(["Alone","Absurd","YOLO"],"Unknown")

df["Marital_Status"].value_counts()

df.dtypes

df["Dt_Customer"].head()

df["Dt_Customer"]= pd.to_datetime(df["Dt_Customer"],format ="%d-%m-%Y")

df["Dt_Customer"].dtype

df[df["Income"]>200000][["ID","Income"]]

df["Year_Birth"].describe()

df.isnull().sum().sum()

df.duplicated().sum()

df.to_csv("cleaned_Marketting_campaign.csv",index=False)

df.to_excel("cleaned_marketting_campaign.xlsx",index=False)

df[df["Income"]>200000][["ID","Income"]]

df["Year_Birth"].describe()

df.loc[df["Income"]==666666,"Income"]=df["Income"].median()

df[df["ID"]==9432][["ID","Income"]]

df[df["Year_Birth"]<1900][["ID","Year_Birth"]]

df["Year_Birth"].value_counts().sort_index().head(15)

import numpy as np

df.loc[df["Year_Birth"]<1900,"Year_Birth"]=np.nan

df["Year_Birth"].median()

df["Year_Birth"]=df["Year_Birth"].fillna(df["Year_Birth"].median())

df["Year_Birth"].isnull().sum()

df.isnull().sum().sum()

df.duplicated().sum()

df.dtypes

# Convert date column to proper datetime
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    format="%d-%m-%Y"
)

# Rename columns to clean, uniform lowercase names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Final checks
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Dataset shape:", df.shape)

df.head()

df.to_csv("cleaned_marketing_campaign.csv", index=False)

df.to_excel("cleaned_marketing_campaign.xlsx", index=False)

print("Files created successfully!")